server:
  port: 7896
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
