server:
  port: 5896
spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
