server:
  port: 8888

spring:
  application:
    name: config-server-service
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:9091 }
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arbilamfarr/config-server.git
          clone-on-start: true
